import Categoria from 'src/categorias/entities/categoria.entity';
import Insumo from 'src/insumos/entities/insumo.entity';
import { DataSource } from 'typeorm';

export class CreateInsumoSeed {
  async run(dataSource: DataSource): Promise<void> {
    const insumoRepository = dataSource.getRepository(Insumo);
    const categoriaRepository = dataSource.getRepository(Categoria);
    
    const categoriaGeneral = await categoriaRepository.findOneBy({ nombre: 'General' });
    const categoriaQuirurgico = await categoriaRepository.findOneBy({ nombre: 'Quirurgico' });
    
    const insumo = [
      { codigo: 'INS-001', nombre: 'Acetaminofen (Paracetamol), Solucion oral, 100mg/1mL', categoria: categoriaGeneral},
      { codigo: 'INS-002', nombre: 'Acetaminofen (Paracetamol), Solucion oral, 120mg/5mL, Frasco', categoria: categoriaGeneral},
      { codigo: 'INS-003', nombre: 'Acetaminofen (Paracetamol), Tableta, 500 mg', categoria: categoriaGeneral},
      { codigo: 'INS-004', nombre: 'Aciclovir tableta', categoria: categoriaGeneral},
      { codigo: 'INS-005', nombre: 'Acido Folico, Tableta, 5 mg', categoria: categoriaGeneral},
      { codigo: 'INS-006', nombre: 'Agua esteril (agua tridestilada), 100 mL,  Vial/Ampolla', categoria: categoriaGeneral},
      { codigo: 'INS-007', nombre: 'Albendazol, Suspension oral, 200mg/5mL, Frasco ', categoria: categoriaGeneral},
      { codigo: 'INS-008', nombre: 'Albendazol, Tableta, 400 mg', categoria: categoriaGeneral},
      { codigo: 'INS-009', nombre: 'Alcohol Etilico 70%, Gel topico', categoria: categoriaGeneral},
      { codigo: 'INS-0010', nombre: 'Alcohol Isopropilico, Solucion topica, 70%, Frasco', categoria: categoriaGeneral},
      { codigo: 'INS-0011', nombre: 'Ambroxol, Jarabe, 15mg/5mL, Frasco', categoria: categoriaGeneral},
      { codigo: 'INS-0012', nombre: 'Amoxicilina + Acido Clavulanico, Suspension oral, 250-62.5mg/5mL, Frasco', categoria: categoriaGeneral},
      { codigo: 'INS-0013', nombre: 'Amoxicilina + Acido Clavulanico, Tableta, 500 mg + 125mg', categoria: categoriaGeneral},
      { codigo: 'INS-0014', nombre: 'Amoxicilina, Suspension oral, 250mg/5mL, Frasco', categoria: categoriaGeneral},
      { codigo: 'INS-0015', nombre: 'Amoxicilina, Tableta/Capsula, 500 mg', categoria: categoriaGeneral},
      { codigo: 'INS-0016', nombre: 'Ampicilina 1 g, Polvo para solucion inyectable Vial/Ampolla', categoria: categoriaGeneral},
      { codigo: 'INS-0017', nombre: 'Acido Hialuronico al 0.25', categoria: categoriaGeneral},
      { codigo: 'INS-0018', nombre: 'Benzocaina Spray', categoria: categoriaGeneral},
      { codigo: 'INS-0019', nombre: 'Azitromicina, Tableta/Capsula, 500 mg', categoria: categoriaGeneral},
      { codigo: 'INS-0020', nombre: 'Benzoato de Bencilo, Solucion topica, 25%, Frasco', categoria: categoriaGeneral},
      { codigo: 'INS-0021', nombre: 'Acido Fosforico', categoria: categoriaGeneral},
      { codigo: 'INS-0022', nombre: 'Calamina, Locion, 5%, Frasco', categoria: categoriaGeneral},
      { codigo: 'INS-0023', nombre: 'Calcio Gluconato, Solucion inyectable, 10%, Vial/Ampolla', categoria: categoriaGeneral},
      { codigo: 'INS-0024', nombre: 'Cefadroxilo, Tableta/Capsula, 500 mg', categoria: categoriaGeneral},
      { codigo: 'INS-0025', nombre: 'Ceftriaxona 1 g, Polvo para solucion inyectable Vial/Ampolla', categoria: categoriaGeneral},
      { codigo: 'INS-0026', nombre: 'Ciprofloxacina, Tableta/Capsula, 500 mg', categoria: categoriaGeneral},
      { codigo: 'INS-0027', nombre: 'Claritromicina, Granulado, 250mg/5mL, Frasco', categoria: categoriaGeneral},
      { codigo: 'INS-0028', nombre: 'Claritromicina, Tableta, 500 mg', categoria: categoriaGeneral},
      { codigo: 'INS-0029', nombre: 'Sellante de Fosas y Fisuras', categoria: categoriaGeneral},
      { codigo: 'INS-0030', nombre: 'Cloranfenicol, Solucion oftalmica, 0.50%, Gotero', categoria: categoriaGeneral},
      { codigo: 'INS-0031', nombre: 'Clorfeniramina Maleato, Jarabe, 2mg/5mL, Frasco', categoria: categoriaGeneral},
      { codigo: 'INS-0032', nombre: 'Clorfeniramina Maleato, Solucion inyectable, 10mg/mL, Vial/Ampolla', categoria: categoriaGeneral},
      { codigo: 'INS-0033', nombre: 'Clorfeniramina Maleato, Tableta, 4 mg', categoria: categoriaGeneral},
      { codigo: 'INS-0034', nombre: 'Clorhexidina gluconato, solución 4%, litro', categoria: categoriaGeneral},
      { codigo: 'INS-0035', nombre: 'Clorhexidina gluconato, jabón 4%, galón', categoria: categoriaGeneral},
      { codigo: 'INS-0036', nombre: 'Clorhexidina gluconato, solución 5%, galón', categoria: categoriaGeneral},
      { codigo: 'INS-0037', nombre: 'Clorhexidina gluconato, solución 5%, litro', categoria: categoriaGeneral},
      { codigo: 'INS-0038', nombre: 'Cloruro de Sodio, Solucion inyectable, 0.90%, Bolsa/Frasco 500 mL', categoria: categoriaGeneral},
      { codigo: 'INS-0039', nombre: 'Clotrimazol, Crema topica, 1%, Tubo/Tarro', categoria: categoriaGeneral},
      { codigo: 'INS-0040', nombre: 'Clotrimazol, Crema vaginal, 2%, Tubo/Tarro', categoria: categoriaGeneral},
      { codigo: 'INS-0041', nombre: 'Albendazol 400mg /10ml frasco', categoria: categoriaGeneral},
      { codigo: 'INS-0042', nombre: 'Dexametasona, Solucion inyectable, 4mg/mL, Vial/Ampolla', categoria: categoriaGeneral},
      { codigo: 'INS-0043', nombre: 'Diclofenaco Sodico, Solucion inyectable, 25mg/mL, Vial/Ampolla', categoria: categoriaGeneral},
      { codigo: 'INS-0044', nombre: 'Dipirona (Metamizol Sodica), Solucion inyectable, 500mg/mL, Vial/Ampolla', categoria: categoriaGeneral},
      { codigo: 'INS-0045', nombre: 'Alfametildopa', categoria: categoriaGeneral},
      { codigo: 'INS-0046', nombre: 'Ciprofibrato 100mg tableta', categoria: categoriaGeneral},
      { codigo: 'INS-0047', nombre: 'Epinefrina Clorhidrato (Adrenalina), 1mg/1mL (1:1000), Vial/Ampolla', categoria: categoriaGeneral},
      { codigo: 'INS-0048', nombre: 'Atorvastatina 20 mg tableta', categoria: categoriaGeneral},
      { codigo: 'INS-0049', nombre: 'Ferroso Sulfato, Tableta/Capsula, 300 mg', categoria: categoriaGeneral},
      { codigo: 'INS-0050', nombre: 'Fluor de Barniz', categoria: categoriaGeneral},
      { codigo: 'INS-0051', nombre: 'Glimepirida, Tableta, 4mg', categoria: categoriaGeneral},
      { codigo: 'INS-0052', nombre: 'Hidralazina Clorhidrato, Solucion inyectable, 20mg/mL, Vial/Ampolla', categoria: categoriaGeneral},
      { codigo: 'INS-0053', nombre: 'Hidrocortisona, Crema topica, 0.25%, Tubo/Tarro', categoria: categoriaGeneral},
      { codigo: 'INS-0054', nombre: 'Hidroxido de aluminio + Magnesio,  Suspension oral, 185mg + 200mg/5mL', categoria: categoriaGeneral},
      { codigo: 'INS-0055', nombre: 'Ibuprofeno, Tableta/Capsula, 400 mg', categoria: categoriaGeneral},
      { codigo: 'INS-0056', nombre: 'Ivermectina 6 mg, tableta', categoria: categoriaGeneral},
      { codigo: 'INS-0057', nombre: 'Kit medicamentos COVID-19, Unidad', categoria: categoriaGeneral},
      { codigo: 'INS-0058', nombre: 'Lansoprazol, Tableta/Capsula, 30 mg', categoria: categoriaGeneral},
      { codigo: 'INS-0059', nombre: 'Lidocaina Clorhidrato sin Epinefrina, sin preservante (simple), Vial/Ampolla', categoria: categoriaGeneral},
      { codigo: 'INS-0060', nombre: 'Lidocaina dental sin Epinefrina, Solucion inyectable, 2%, Cartucho 1.8 mL', categoria: categoriaGeneral},
      { codigo: 'INS-0061', nombre: 'Losartan Potasico, Tableta, 50 mg', categoria: categoriaGeneral},
      { codigo: 'INS-0062', nombre: 'Magnesio Sulfato, Solucion inyectable, 50%, Vial/Ampolla', categoria: categoriaGeneral},
      { codigo: 'INS-0063', nombre: 'Metformina, Tableta, 850 mg', categoria: categoriaGeneral},
      { codigo: 'INS-0064', nombre: 'Metronidazol + Nistatina, Ovulo, 500 mg + 100,000 UI', categoria: categoriaGeneral},
      { codigo: 'INS-0065', nombre: 'Metronidazol, Suspension oral, 125mg/5mL, Frasco', categoria: categoriaGeneral},
      { codigo: 'INS-0066', nombre: 'Metronidazol, Tableta/Capsula, 500 mg', categoria: categoriaGeneral},
      { codigo: 'INS-0067', nombre: 'Misoprostol, Tableta, 200 mcg', categoria: categoriaGeneral},
      { codigo: 'INS-0068', nombre: 'Irbesartan  tableta', categoria: categoriaGeneral},
      { codigo: 'INS-0069', nombre: 'Nifedipina, Tableta/Capsula, 10 mg', categoria: categoriaGeneral},
      { codigo: 'INS-0070', nombre: 'Nistatina, Suspension oral, 100,000 UI/mL, Gotero', categoria: categoriaGeneral},
      { codigo: 'INS-0071', nombre: 'Oxido de Zinc + almidon de maiz (Pasta Lassar), Pasta, 25%, Tubo/Tarro', categoria: categoriaGeneral},
      { codigo: 'INS-0072', nombre: 'Oxitocina Sintetica, Solucion inyectable, 5 UI/mL, Vial/Ampolla', categoria: categoriaGeneral},
      { codigo: 'INS-0073', nombre: 'Penicilina G Benzatinica, Polvo liofilizado, 1,200,000 UI, Vial/Ampolla', categoria: categoriaGeneral},
      { codigo: 'INS-0074', nombre: 'Penicilina Procaina,  Polvo liofilizado, 4,000,000 UI, Vial/Ampolla', categoria: categoriaGeneral},
      { codigo: 'INS-0075', nombre: 'Peroxido de Hidrogeno (agua oxigenada), Solucion topica, 3%, Frasco', categoria: categoriaGeneral},
      { codigo: 'INS-0076', nombre: 'Propinoxato + Clonixinato de Lisina, 15mg + 100mg, Vial/Ampolla', categoria: categoriaGeneral},
      { codigo: 'INS-0077', nombre: 'Eugenol + Yodoformo', categoria: categoriaGeneral},
      { codigo: 'INS-0078', nombre: 'Pasta para profilaxis', categoria: categoriaGeneral},
      { codigo: 'INS-0079', nombre: 'Salbutamol Sulfato, Jarabe, 2mg/5mL, Frasco', categoria: categoriaGeneral},
      { codigo: 'INS-0080', nombre: 'Salbutamol Sulfato, Solución para inhalación, 5mg/ml, Gotero', categoria: categoriaGeneral},
      { codigo: 'INS-0081', nombre: 'Sales de Rehidratacion Oral,  Polvo, 3.5g + 2.9g + 1.5g + 20g, Sobre 27.90 g', categoria: categoriaGeneral},
      { codigo: 'INS-0082', nombre: 'Solucion de Hartman 1000 mL, 0.6g + 0.31g + 0.03g + 0.02g/100mL, Bolsa/Frasco', categoria: categoriaGeneral},
      { codigo: 'INS-0083', nombre: 'Solucion de Hartman 500 mL, 0.6g + 0.31g + 0.03g + 0.02g/100mL, Bolsa/Frasco', categoria: categoriaGeneral},
      { codigo: 'INS-0084', nombre: 'Sulfacetamida Sodica, Solucion oftalmica, 10%, Gotero', categoria: categoriaGeneral},
      { codigo: 'INS-0085', nombre: 'Sulfadiazina de Plata, Crema topica, 1%, Tubo/Tarro', categoria: categoriaGeneral},
      { codigo: 'INS-0086', nombre: 'Sulfato de Zinc, Tableta/Capsula, 20mg', categoria: categoriaGeneral},
      { codigo: 'INS-0087', nombre: 'Tinidazol, Tableta/Capsula, 500 mg', categoria: categoriaGeneral},
      { codigo: 'INS-0088', nombre: 'Trimetoprima + Sulfametoxazol, Suspension oral, 40-200mg/5mL, Frasco', categoria: categoriaGeneral},
      { codigo: 'INS-0089', nombre: 'Trimetoprima + Sulfametoxazol, Tableta, 160mg + 800 mg', categoria: categoriaGeneral},
      { codigo: 'INS-0090', nombre: 'Fluconazol tableta', categoria: categoriaGeneral},
      { codigo: 'INS-0091', nombre: 'Vitamina D 1 mg, tableta', categoria: categoriaGeneral},
      { codigo: 'INS-0092', nombre: 'Vitamina K1  Solucion inyectable, 10mg/mL, Vial/Ampolla', categoria: categoriaGeneral},
      { codigo: 'INS-0093', nombre: 'Vitaminas Neurotropas , Solucion Inyectable, Ampolla', categoria: categoriaGeneral},
      { codigo: 'INS-0094', nombre: 'Alimento Complementario Fortificado, Bolsa', categoria: categoriaGeneral},
      { codigo: 'INS-0095', nombre: 'Alimento Terapeutico,  Sobre 92 g', categoria: categoriaGeneral},
      { codigo: 'INS-0096', nombre: 'INCAPARINA CRECIMAX Bolsa 1 Libra', categoria: categoriaGeneral},
      { codigo: 'INS-0097', nombre: 'INCAPARINA MATERNAL Bolsa 1 Libra', categoria: categoriaGeneral},
      { codigo: 'INS-0098', nombre: 'Mi Comidita Sin concentracion, Bolsa Unidad', categoria: categoriaGeneral},
      { codigo: 'INS-0099', nombre: 'Micronutrientes Espolvoreables  Sobre', categoria: categoriaGeneral},
      { codigo: 'INS-0100', nombre: 'Vitamina A (Retinol) 100,000 UI, Perla', categoria: categoriaGeneral},
      { codigo: 'INS-0101', nombre: 'Vitamina A (Retinol) 50,000 UI, Perla', categoria: categoriaGeneral},
      { codigo: 'INS-0102', nombre: 'Condon masculino', categoria: categoriaGeneral},
      { codigo: 'INS-0103', nombre: 'Collar de ciclo, sobre unidad', categoria: categoriaGeneral},
      { codigo: 'INS-0104', nombre: 'Enantato de Noretisterona + Valerato de Estradiol 50mg+ 5 mg, Ampolla/Jeringa Prellenada', categoria: categoriaGeneral},
      { codigo: 'INS-0105', nombre: 'Enantato de Noretisterona, 200 mg, Vial/Ampolla (NORISTERAT)', categoria: categoriaGeneral},
      { codigo: 'INS-0106', nombre: 'Jeringa Pregarcada de Mesigyna, Unidad', categoria: categoriaGeneral},
      { codigo: 'INS-0107', nombre: 'Levonorgestrel + Etinilestradiol + Fumarato Ferroso  0.15mg + 0.03mg + 75mg, ciclo', categoria: categoriaGeneral},
      { codigo: 'INS-0108', nombre: 'Levonorgestrel 1.5mg, Tableta', categoria: categoriaGeneral},
      { codigo: 'INS-0109', nombre: 'Levonorgestrel 75 mg, Implante', categoria: categoriaGeneral},
      { codigo: 'INS-0110', nombre: 'Medroxiprogesterona Acetato  , Suspension inyectable, 150mg/mL, Vial/Ampolla', categoria: categoriaGeneral},
      { codigo: 'INS-0111', nombre: 'T de cobre (DIU), Dispositivo intrauterino', categoria: categoriaGeneral},
      { codigo: 'INS-0112', nombre: 'T de cobre (DIU), Dispositivo intrauterino 380A postparto', categoria: categoriaGeneral},
      { codigo: 'INS-0113', nombre: 'Hidroclorotiazida 50mg tableta', categoria: categoriaGeneral},
      { codigo: 'INS-0114', nombre: 'Fucsina Fenicada', categoria: categoriaGeneral},
      { codigo: 'INS-0115', nombre: 'Azul de Metileno', categoria: categoriaGeneral},
      { codigo: 'INS-0116', nombre: 'Alcohol Acido', categoria: categoriaGeneral},
      { codigo: 'INS-0117', nombre: 'Servilletas Odontologia', categoria: categoriaGeneral},
      { codigo: 'INS-0118', nombre: 'Jeringa Descartable 5ml', categoria: categoriaGeneral},
      { codigo: 'INS-0119', nombre: 'Eyectores', categoria: categoriaGeneral},
      { codigo: 'INS-0120', nombre: 'Hilo Dental', categoria: categoriaGeneral},
      { codigo: 'INS-0121', nombre: 'Emtricitabina + Tenofovir 200/300 mg, Tableta', categoria: categoriaGeneral},
      { codigo: 'INS-0122', nombre: 'Etambutol Clorhidrato  400 mg, Tableta', categoria: categoriaGeneral},
      { codigo: 'INS-0123', nombre: 'Isoniazida INH 100 mg, Tableta', categoria: categoriaGeneral},
      { codigo: 'INS-0124', nombre: 'Isoniazida INH 300 mg, Tableta', categoria: categoriaGeneral},
      { codigo: 'INS-0125', nombre: 'Lamivudina + Zidovudina 150/300 mg, Tableta', categoria: categoriaGeneral},
      { codigo: 'INS-0126', nombre: 'Lamivudina 150 mg, Tableta', categoria: categoriaGeneral},
      { codigo: 'INS-0127', nombre: 'QLamivudina 50 mg/5mL, Suspensión oral', categoria: categoriaGeneral},
      { codigo: 'INS-0128', nombre: 'Lopinavir + Ritonavir 400mg + 100mg/5mL, Solucion oral', categoria: categoriaGeneral},
      { codigo: 'INS-0129', nombre: 'Nevirapina 50 mg/ 5 mL, Suspensión Oral', categoria: categoriaGeneral},
      { codigo: 'INS-0130', nombre: 'Nifurtimox, Tableta 120 mg', categoria: categoriaGeneral},
      { codigo: 'INS-0131', nombre: 'Pirazinamida  500mg, Tableta', categoria: categoriaGeneral},
      { codigo: 'INS-0132', nombre: 'Primaquina, Tableta 15 mg', categoria: categoriaGeneral},
      { codigo: 'INS-0133', nombre: 'Primaquina, Tableta 5 mg', categoria: categoriaGeneral},
      { codigo: 'INS-0134', nombre: 'Protionamida 250 mg, Tableta', categoria: categoriaGeneral},
      { codigo: 'INS-0135', nombre: 'Raltegravir 400 mg, Tableta', categoria: categoriaGeneral},
      { codigo: 'INS-0136', nombre: 'Rifampicina  300 mg, Capsula', categoria: categoriaGeneral},
      { codigo: 'INS-0137', nombre: 'Rifampicina + isoniazida + pirazinamida + etambutol 150 mg + 75 mg + 400 mg + 275 mg, Tableta', categoria: categoriaGeneral},
      { codigo: 'INS-0138', nombre: 'Rifampicina + isoniazida + pirazinamida 75 mg + 50 mg + 150mg, Tableta', categoria: categoriaGeneral},
      { codigo: 'INS-0139', nombre: 'Rifampicina + isoniazida 150 mg + 75 mg, Tableta', categoria: categoriaGeneral},
      { codigo: 'INS-0140', nombre: 'Rifampicina + isoniazida 75 mg + 50 mg, Tableta', categoria: categoriaGeneral},
      { codigo: 'INS-0141', nombre: 'Rifapentina + Isoniazida 300 mg + 300 mg, Tableta', categoria: categoriaGeneral},
      { codigo: 'INS-0142', nombre: 'Tenofovir  Disopropil fumarato 300 mg, Tableta', categoria: categoriaGeneral},
      { codigo: 'INS-0143', nombre: 'Zidovudina 10 mg/mL, Solución Inyectable', categoria: categoriaGeneral},
      { codigo: 'INS-0144', nombre: 'Zidovudina 50 mg/5 ml, Suspensión Oral', categoria: categoriaGeneral},
      { codigo: 'INS-0145', nombre: 'KARDEX A', categoria: categoriaGeneral},
      { codigo: 'INS-0146', nombre: 'KARDEX B', categoria: categoriaGeneral},
      { codigo: 'INS-0147', nombre: 'KARDEX C', categoria: categoriaGeneral},
      { codigo: 'INS-0148', nombre: 'KARDEX D', categoria: categoriaGeneral},
      { codigo: 'INS-0149', nombre: 'KARDEX E', categoria: categoriaGeneral},
      { codigo: 'INS-0150', nombre: 'KARDEX F', categoria: categoriaGeneral},
      { codigo: 'INS-0151', nombre: 'KARDEX G', categoria: categoriaGeneral},
      { codigo: 'INS-0152', nombre: 'KARDEX H', categoria: categoriaGeneral},
      { codigo: 'INS-0153', nombre: 'KARDEX I', categoria: categoriaGeneral},
      { codigo: 'INS-0154', nombre: 'KARDEX J', categoria: categoriaGeneral},
      { codigo: 'INS-0155', nombre: 'KARDEX K', categoria: categoriaGeneral},
      { codigo: 'INS-0156', nombre: 'KARDEX L', categoria: categoriaGeneral},
      { codigo: 'INS-0157', nombre: 'KARDEX M', categoria: categoriaGeneral},
      { codigo: 'INS-0158', nombre: 'KARDEX N', categoria: categoriaGeneral},
      { codigo: 'INS-0159', nombre: 'Acido Acético, Frasco', categoria: categoriaQuirurgico},
      { codigo: 'INS-0160', nombre: 'Aguja uso dental 27G x 1 1/2" larga, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0161', nombre: 'Aguja uso dental 27G x 3/4 " corta, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0162', nombre: 'Algodon absorbente 100% puro, Rollo', categoria: categoriaQuirurgico},
      { codigo: 'INS-0163', nombre: 'Algodon para uso odontologico, Rollo liso No. 2', categoria: categoriaQuirurgico},
      { codigo: 'INS-0164', nombre: 'Bata Quirurgica descartable no esteril talla unica. Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0165', nombre: 'Bolsa para recoleccion urinaria  para pierna, capacidad 500 - 900 mL ventilada., Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0166', nombre: 'Canula binasal, para administracion de oxigeno adulto, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0167', nombre: 'Cateter intravenoso No. 18G., Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0168', nombre: 'Cateter intravenoso No. 20G., Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0169', nombre: 'Cateter intravenoso No. 22G., Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0170', nombre: 'Cateter intravenoso No. 24G. Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0171', nombre: 'Cinta testigo para esterilizacion con vapor , Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0172', nombre: 'Clamp umbilical, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0173', nombre: 'Termometro Frontal', categoria: categoriaQuirurgico},
      { codigo: 'INS-0174', nombre: 'Papel Limpialente', categoria: categoriaQuirurgico},
      { codigo: 'INS-0175', nombre: 'Curitas Redondas, Caja Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0176', nombre: 'Depresor de lengua (bajalenguas), Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0177', nombre: 'Equipo para venoclisis, sin aguja,  con camara de goteo transparente de 20 gotas/ml, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0178', nombre: 'Resucitador ambu adulto', categoria: categoriaQuirurgico},
      { codigo: 'INS-0179', nombre: 'Esparadrapo de seda impermeable 1 pulgada, Rollo', categoria: categoriaQuirurgico},
      { codigo: 'INS-0180', nombre: 'Esparadrapo de seda impermeable 2 pulgadas, Rollo', categoria: categoriaQuirurgico},
      { codigo: 'INS-0181', nombre: 'Esparadrapo de seda impermeable 3 pulgadas, Rollo', categoria: categoriaQuirurgico},
      { codigo: 'INS-0182', nombre: 'Pipeta Amarilla', categoria: categoriaQuirurgico},
      { codigo: 'INS-0183', nombre: 'Esparadrapo microporoso sintetico  1 pulgada, Rollo', categoria: categoriaQuirurgico},
      { codigo: 'INS-0184', nombre: 'Esparadrapo microporoso sintetico  2 pulgadas, Rollo', categoria: categoriaQuirurgico},
      { codigo: 'INS-0185', nombre: 'Esparadrapo microporoso sintetico  3 pulgadas, Rollo', categoria: categoriaQuirurgico},
      { codigo: 'INS-0186', nombre: 'Espatula o Paleta de Ayre, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0187', nombre: 'Bachitas Redondas  unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0188', nombre: 'Especulo vaginal descartable mediano, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0189', nombre: 'Frascos esteriles para muestra de orina Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0190', nombre: 'Gasa quirurgica de 36"x 100 yardas, Pieza', categoria: categoriaQuirurgico},
      { codigo: 'INS-0191', nombre: 'Gel lubricante, Sobre/Sachet Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0192', nombre: 'Gel o jalea lubricante hidrosoluble con bacteriostatico, Tubo', categoria: categoriaQuirurgico},
      { codigo: 'INS-0193', nombre: 'Gorro descartable para cirujano, Caja Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0194', nombre: 'Guante descartable de latex grande, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0195', nombre: 'Guante descartable de latex mediano, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0196', nombre: 'Guante descartable de latex pequeño, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0197', nombre: 'Guante quirurgico No. 6, Par Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0198', nombre: 'Guante quirurgico No. 6 1/2, Par Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0199', nombre: 'Guante quirurgico No. 7, Par Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0200', nombre: 'Guante quirurgico No. 7 1/2, Par Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0201', nombre: 'Hisopo de madera, no esteril.', categoria: categoriaQuirurgico},
      { codigo: 'INS-0202', nombre: 'Hoja de Bisturi No. 20, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0203', nombre: 'Hoja de Bisturi No. 21, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0204', nombre: 'Hoja de Bisturi No. 22, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0205', nombre: 'Hoja de Bisturi No. 23, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0206', nombre: 'Hoja de Bisturi No. 24, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0207', nombre: 'Jeringa descartable PSR, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0208', nombre: 'Jeringa descartable 10 mL, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0209', nombre: 'Jeringa descartable 3 mL, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0210', nombre: 'Jeringa descartable 5 mL., Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0211', nombre: 'Lamina Cubreobjetos. Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0212', nombre: 'Lamina Portaobjetos. Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0213', nombre: 'Lanceta. Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0214', nombre: 'Gel Lubricante galon', categoria: categoriaQuirurgico},
      { codigo: 'INS-0215', nombre: 'Mascarilla quirurgica descartable, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0216', nombre: 'Mascarilla tipo respirador N95/KN95, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0217', nombre: 'Termometro de Laboratorio', categoria: categoriaQuirurgico},
      { codigo: 'INS-0218', nombre: 'Papel kraft , Bobina', categoria: categoriaQuirurgico},
      { codigo: 'INS-0219', nombre: 'Recipiente Punzo Cortante', categoria: categoriaQuirurgico},
      { codigo: 'INS-0220', nombre: 'Prueba Hepatitis C', categoria: categoriaQuirurgico},
      { codigo: 'INS-0221', nombre: 'Protector facial (careta), Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0222', nombre: 'Prueba para Rotavirus. Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0223', nombre: 'Prueba rapida de Embarazo. Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0224', nombre: 'Prueba rapida para Helicobacter Pylori en Heces Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0225', nombre: 'Prueba rapida para Hepatitis A. Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0226', nombre: 'Prueba rapida para Hepatitis B. Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0227', nombre: 'Prueba rapida para Sifilis (simple). Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0228', nombre: 'Prueba rapida para VIH. Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0229', nombre: 'Prueba rápida para deteccion de SARS COVID-19 en hisopado', categoria: categoriaQuirurgico},
      { codigo: 'INS-0230', nombre: 'Humificador de Oxigeno', categoria: categoriaQuirurgico},
      { codigo: 'INS-0231', nombre: 'Ligadura de Hule', categoria: categoriaQuirurgico},
      { codigo: 'INS-0232', nombre: 'Reactivo de Rh (Grupo sanguineo A, B y D), Kit Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0233', nombre: 'Recipiente para muestra de BK. Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0234', nombre: 'Recipiente para muestra de heces, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0235', nombre: 'Recipiente para muestra de orina, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0236', nombre: 'Seda negra 1-0 no abosrbible trenzada, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0237', nombre: 'Seda negra 2-0 no absorbible trenzada, unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0238', nombre: 'Seda negra 3-0 no absorbible trenzada, unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0239', nombre: 'Seda negra 4-0 no absorbible trenzada, unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0240', nombre: 'Seda negra 5-0 no absorbible trenzada, unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0241', nombre: 'Sonda Foley  No. 16 Fr., Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0242', nombre: 'Sonda Foley  No. 18 Fr., Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0243', nombre: 'Spray fijador, Frasco', categoria: categoriaQuirurgico},
      { codigo: 'INS-0244', nombre: 'Sutura Nylon (Poliamida) 2-0, monofilamento, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0245', nombre: 'Sutura Nylon (Poliamida) 3-0, monofilamento, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0246', nombre: 'Sutura Nylon (Poliamida) 4-0, monofilamento, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0247', nombre: 'Sutura Nylon (Poliamida) 5-0, monofilamento . Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0248', nombre: 'Sutura Sintetica Absorbible 0-0, multifilamento, Sobre', categoria: categoriaQuirurgico},
      { codigo: 'INS-0249', nombre: 'Sutura Sintetica Absorbible 1-0, multifilamento, Sobre', categoria: categoriaQuirurgico},
      { codigo: 'INS-0250', nombre: 'Sutura Sintetica Absorbible 2-0, multifilamento, Sobre', categoria: categoriaQuirurgico},
      { codigo: 'INS-0251', nombre: 'Sutura Sintetica Absorbible 3-0, multifilamento, Sobre', categoria: categoriaQuirurgico},
      { codigo: 'INS-0252', nombre: 'Sutura Sintetica Absorbible 4-0, multifilamento, Sobre', categoria: categoriaQuirurgico},
      { codigo: 'INS-0253', nombre: 'Termómetro digital, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0254', nombre: 'Termometro clinico oral, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0255', nombre: 'Termometro infrarrojo, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0256', nombre: 'Tira reactiva para Glucosa en sangre. Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0257', nombre: 'Tira reactiva para Orina, Frasco Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0258', nombre: 'Pruebas Sangre oculta en heces', categoria: categoriaQuirurgico},
      { codigo: 'INS-0259', nombre: 'Tubo de vidrio de 5 mL, sin aditivo. Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0260', nombre: 'Tubo para extraccion al Vacio de 10 ml, sin aditivo. Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0261', nombre: 'Tubo para extraccion al Vacio de 3 ml, con EDTA. Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0262', nombre: 'Venda elastica de 2" x 5 yardas, Rollo', categoria: categoriaQuirurgico},
      { codigo: 'INS-0263', nombre: 'Venda elastica de 4" x 5 yardas, Rollo', categoria: categoriaQuirurgico},
      { codigo: 'INS-0264', nombre: 'Venda elastica de 6" x 5 yardas, Rollo', categoria: categoriaQuirurgico},
      { codigo: 'INS-0265', nombre: 'Zapatones para area quirurgica, Unidad', categoria: categoriaQuirurgico},
      { codigo: 'INS-0266', nombre: 'Sonda Nasogastrico Calibre 5', categoria: categoriaQuirurgico},
      { codigo: 'INS-0267', nombre: 'Sonda Nasogastrico Calibre 8', categoria: categoriaQuirurgico},
      { codigo: 'INS-0268', nombre: 'Microcubeta desartable', categoria: categoriaQuirurgico},
      { codigo: 'INS-0269', nombre: 'Mascarilla N95', categoria: categoriaQuirurgico},
      { codigo: 'INS-0270', nombre: 'Cinta Castilla', categoria: categoriaQuirurgico},
      { codigo: 'INS-0271', nombre: 'Tira reactiva para determinació de trioliceridos', categoria: categoriaQuirurgico},
      { codigo: 'INS-0272', nombre: 'Prueba confirmatoria VIH', categoria: categoriaQuirurgico},
      { codigo: 'INS-0273', nombre: 'Cepillo para profilaxis', categoria: categoriaQuirurgico},
      { codigo: 'INS-0274', nombre: 'Prueba de embarazo en Sangre', categoria: categoriaQuirurgico},
      { codigo: 'INS-0275', nombre: 'Termometro de alcohol', categoria: categoriaQuirurgico},
      { codigo: 'INS-0276', nombre: 'Prueba Hemoglobina', categoria: categoriaQuirurgico},
      { codigo: 'INS-0277', nombre: 'KARDEX Y', categoria: categoriaQuirurgico},
      { codigo: 'INS-0278', nombre: 'KARDEX Z', categoria: categoriaQuirurgico},
    ];

    await insumoRepository.save(insumo);
  }
}